
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env.local
    command: npm run dev
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    command: npm run start:dev
    networks:
      - app-network
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

networks:
  app-network:
    driver: bridge